replicaCount: 1
image:
  repository: atlassian/bitbucket
  pullPolicy: IfNotPresent
  tag: "8.9.14"
bitbucket:
  mode: mirror
  displayName: Bitbucket Mirror Farm
  clustering:
    enabled: true
  applicationMode: "mirror"
  mirror:
    upstreamUrl: ":q!
    " # Update this
  service:
    contextPath: 
  readinessProbe:
    # -- Whether to apply the readinessProbe check to pod.
    #
    enabled: false
  additionalEnvironmentVariables:
    - name: SETUP_BASEURL
      value: "https://k8s-76096.prod.atl-cd.net"
    - name: SERVER_CONTEXT-PATH
      value: 
ingress:
  create: true
  host: "k8s-76096.prod.atl-cd.net" 
  path: 
  tlsSecretName: atl-cd-certificate
volumes:
  localHome:
    persistentVolumeClaim:
      create: true